# frozen_string_literal: true

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#-----------------------------------------------------------------------------------------------------------------------------------------------#

def process_range
  for_store_number = []
  num1 = 0
  num2 = 1
  num3 = 0
  loop do
    num3 = num1 + num2
    break if num3 > 4_000_000

    for_store_number.push num3 if num3.even?
    num1 = num2
    num2 = num3
  end
  sum = addition(for_store_number)
end

def addition(for_store_number)
  sum = for_store_number.inject { |sum, num| sum + num }
  sum
 end

puts process_range
